[project]
name = "dj-template-harness"
version = "0.1.0"
description = ""
authors = [
    {name = "DSA NTC", email = "ntc@dsacommittees.org"},
]
dependencies = [
    "django>=4.2.7",
    "ruff>=0.1.5",
    "django-extensions>=3.2.3",
    "werkzeug>=3.0.1",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
server = "python manage.py runserver_plus"

[tool.ruff]
select=["ALL"]
fix=true

[tool.ruff.lint.pydocstyle]
convention = "google"
