[project]
name = ""
version = ""
description = ""
authors = [
    {name = "DSA NTC", email = "ntc@dsacommittees.org"},
]
dependencies = [
    "django>=4.2.7",
    "ruff>=0.1.3",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

